# Generated by Django 3.2 on 2022-03-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipnumber',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.product'),
        ),
    ]
