# Generated by Django 3.2 on 2022-03-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('checkout', '0003_createmembership_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='createmembership',
            name='membership_typ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_typ', to='membership.product'),
        ),
    ]
