# Generated by Django 3.2 on 2022-04-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
        ('checkout', '0004_createmembership_membership_typ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createmembership',
            name='membership_typ',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_typ', to='membership.product'),
        ),
    ]
