# Generated by Django 3.2 on 2022-03-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='time',
            field=models.CharField(blank=True, choices=[(0, '14:00-15:00'), (1, '16:00-17:00'), (2, '20:00-21:00')], max_length=10, null=True),
        ),
    ]
